initial implementation for pixels with streaming
databricks-industry-solutions/pixels pull request #49
Opened 2024-02-27 16:38 UTC by erinaldidb

To enable the streaming capability a parameter is required in catalog reading step.

```python
from dbx.pixels import Catalog
from dbx.pixels.dicom import DicomPlot
from dbx.pixels.dicom import DicomMetaExtractor, DicomThumbnailExtractor

catalog = Catalog(spark, table+"_stream")
catalog_df = catalog.catalog(path, streaming=True)
```

2024-02-27 17:28 UTC, dmoore247 commented
Note that test and lint failed.
@erinaldidb Please run `make style` and update PR.

2024-02-27 17:34 UTC, dmoore247 requested changes
Excellent work!!
Make checkpoint a parameter, a volume.
Please add a python 'unit' test if at all possible (runs with `make test`)

2024-02-27 17:34 UTC, dmoore247 commented on dbx/pixels/catalog.py
> +                streamCheckpointPath: str = "/tmp/pixels_checkpoints/",
The checkpoint path should be a volume and a parameter.

2024-02-28 22:46 UTC, dmoore247 approved these changes
LGTM!
See in-line question.

2024-02-28 22:46 UTC, dmoore247 commented on tests/dbx/test_stream.py
> +        if "No file or directory exists on path" in str(err):
Will error return the path that was attempted or do we have to provide the context?

2024-02-29 13:09 UTC, erinaldidb commented on tests/dbx/test_stream.py
> +        if "No file or directory exists on path" in str(err):
Yes, it will also return the path you requested to list from.

2024-02-29 13:09 UTC, merged