MONAILabel Integration
databricks-industry-solutions/pixels pull request #63
Opened 2024-10-21 17:52 UTC by erinaldidb

- MONAILabel server ready to be executed in databricks' workspaces.
- Updated OHIF viewer to integrate MONAILabel extension.
- Added export to databricks capability for segmentations and measurements.
- Updated PYDICOM version to 2.4.4
- Removed dbtunnel dependency
- Updated README

2024-10-21 21:04 UTC, dmoore247 requested changes
Mostly comments, optional.
License change in README - required.

2024-10-21 21:04 UTC, dmoore247 commented on 05-MONAILabel.py
> +displayHTML(f"<h1>Use the following link as MONAILabel server address</h1><br><h2>https://dbc-dp-{get_context().workspaceId}.cloud.databricks.com/driver-proxy/o/{get_context().workspaceId}/{get_conte
This is a different base URL than the one a few lines above. Curious as to if one is better than the other. Do we know of any issues across the 2-3 clouds?

2024-10-21 21:04 UTC, dmoore247 commented on 05-MONAILabel.py
> +# MAGIC monailabel start_server --app /local_disk0/monai/apps/radiology --studies $DATABRICKS_HOST --conf models segmentation --table $DATABRICKS_PIXELS_TABLE
Temp storage `/local_disk0/monai/apps/radiology` ?
It would be good to document to help answer any security review questions.

2024-10-21 21:04 UTC, dmoore247 commented on 06-OHIF-Viewer.py
> +app.add_route("/sqlwarehouse/api/2.0/fs/files/{path:path}", _reverse_proxy_files, ["GET", "PUT"])
Which token, which identity is used with the SQL Warehouse? The end user's?

2024-10-21 21:04 UTC, dmoore247 commented on 06-OHIF-Viewer.py
> -from dbtunnel import dbtunnel
no longer needed, or replacing it is better?

2024-10-21 21:04 UTC, dmoore247 commented on README.md
> +[![DBR](https://img.shields.io/badge/DBR-14.3ML-red?logo=databricks&style=for-the-badge)](https://docs.databricks.com/release-notes/runtime/14.3ml.html)
Nice touch!

2024-10-21 21:04 UTC, dmoore247 commented on README.md
> +To run this accelerator, clone this repo into a Databricks workspace. Attach the `RUNME` notebook to any cluster running a DBR 14.3 LTS or later runtime, and execute the notebook via Run-All. A multi
Nice!

2024-10-21 21:04 UTC, dmoore247 commented on README.md
> +| MONAILabel           | Intelligent open source image labeling and learning tool | Apache Software License (BSD)  | https://github.com/Project-MONAI/MONAILabel |
Should be `| Apache License 2.0 |`

2024-10-21 21:30 UTC, erinaldidb commented on 05-MONAILabel.py
> +displayHTML(f"<h1>Use the following link as MONAILabel server address</h1><br><h2>https://dbc-dp-{get_context().workspaceId}.cloud.databricks.com/driver-proxy/o/{get_context().workspaceId}/{get_conte
DATABRICKS_HOST is the current workspace url and is needed for the rest sql and file api while the dbc-dp is the proxy address to access webUIs hosted in the driver, SPARKUI is using a similar approach.

`Need to to double check for Azure and GCP. `

2024-10-21 21:31 UTC, erinaldidb commented on 05-MONAILabel.py
> +# MAGIC monailabel start_server --app /local_disk0/monai/apps/radiology --studies $DATABRICKS_HOST --conf models segmentation --table $DATABRICKS_PIXELS_TABLE
Correct, it will be used to download the latest model and will save the partial results of the segmentations. /tmp/ is also an option here (maybe slower?)

2024-10-21 21:32 UTC, erinaldidb commented on 06-OHIF-Viewer.py
> +app.add_route("/sqlwarehouse/api/2.0/fs/files/{path:path}", _reverse_proxy_files, ["GET", "PUT"])
Correct, the user that executes the notebook. Since the cluster will be SingleUser then UC rows filtering and column masking features work as expected.

2024-10-21 21:33 UTC, erinaldidb commented on 06-OHIF-Viewer.py
> -from dbtunnel import dbtunnel
No longer needed. UVICORN is enough for the job.

2024-10-21 21:34 UTC, erinaldidb commented on README.md
> +| MONAILabel           | Intelligent open source image labeling and learning tool | Apache Software License (BSD)  | https://github.com/Project-MONAI/MONAILabel |
Updated

2024-10-23 15:01 UTC, dmoore247 approved these changes
LGTM!

2024-10-23 15:15 UTC, merged